import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F3F7F7] min-h-screen flex flex-col`}>
        <main className="flex flex-col items-center justify-between flex-1">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
